### ISSUE TITLE
Music Player

### ISSUE THREAD

**Issue by themythia** [chingu-voyages/v35-geckos-team-06#13]
**__Feature Description__**
User can play the selected song.

**__Major User Stories/tasks__**
- [x] Ability to control music (pause/play)
- [x] Ability to move next or previous song
- [x] Ability to change volume of the song
- [x] Ability to shuffle songs in a playlist/album
- [x] Ability to loop songs
- [x] Ability to skip to selected playback time
