### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by themythia** [chingu-voyages/v35-geckos-team-06#14]
**__Feature Description__**
Show the user recommended music and recent played list.
**__Major User Stories/tasks__**
- [x] Users can see music/album recommended to their taste
- [x] Users can see their recently played music
- [x] Users can see currently playing music
